trigger: none

pool:
 name: TF

variables:
 - group: MyKeyVaultVariableGroup

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'KV-SP'
    KeyVaultName: 'Demotfkey'
    SecretsFilter: '*'
    RunAsPreJob: true
- script: echo $(MySecret)
  displayName: 'Display Secret' 