trigger: none

pool:
 name: TF

variables:
  - name: "demovar"
    value: "demovalue"


stages:
  - stage: Deploy
    jobs:
      - deployment: Test
        environment: test
        strategy:
         runOnce:
            deploy:
              steps:
                - checkout: self
                - script: echo "varibale defined"
         
        


