trigger: none

pool:
 name: TF

variables:
 - group: MyKeyVaultVariableGroup

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Free Trial(ebf7697d-eeb4-42b2-93fb-0b0022b90ffa)'
    KeyVaultName: 'Demotfkey'
    SecretsFilter: '*'
    RunAsPreJob: true
- script: echo $(MySecret)
  displayName: 'Display Secret'