trigger: none

pool:
 name: TF

variables:
  azuresubcription: KV-SP
  keyvaultname: Demotfkey
  secretName: my-secret
  secretValue: my-secret-value

stages:
  - stage: UpdatekeyVault
    displayName: "update keyvult"
    jobs:
      - job: updatesecret
        displayName: "update secret"
        steps:
          -  task: AzureCLI@2
             displayName: "update kv"
             inputs:
                azureSubscription: $(azuresubcription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                   az keyvault secret set --valut-name $(keyvaultname) --name $(secretName) --value $(secretValue)