trigger:
 - master 
stages:
  - stage: StageA
    pool: 
     vmImage: ubuntu-latest
    jobs:
      - job: JobA
        displayName: This is job A
      - job: JobB
        displayName: this is job b
        pool: 
         vmImage: windows-lates

